# Generated by Django 4.2.3 on 2023-11-19 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Станок',
                'verbose_name_plural': 'Станки',
                'db_table': 'pf_machine',
            },
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time_ms', models.IntegerField(verbose_name='Время цикла')),
                ('id_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpa.machine')),
            ],
            options={
                'verbose_name': 'Цикл',
                'verbose_name_plural': 'Циклы',
                'db_table': 'pf_cycle',
            },
        ),
    ]
