# Generated by Django 4.2.3 on 2023-11-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['id'], 'verbose_name': 'Станок', 'verbose_name_plural': 'Станки'},
        ),
        migrations.AlterField(
            model_name='cycle',
            name='date',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
    ]
