# Generated by Django 4.2.3 on 2023-11-20 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpa', '0002_alter_machine_options_alter_cycle_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cycle',
            table='tpa_cycle',
        ),
        migrations.AlterModelTable(
            name='machine',
            table='tpa_machine',
        ),
    ]
