# Generated by Django 4.2.3 on 2023-11-22 07:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tpa', '0003_alter_cycle_table_alter_machine_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
