# Generated by Django 4.2.3 on 2023-12-04 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpa', '0005_cycle_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cycle',
            name='counter',
        ),
    ]
