# Generated by Django 4.2.3 on 2023-12-04 12:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tpa', '0006_remove_cycle_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.IntegerField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('number', models.CharField(max_length=50, verbose_name='Номер')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
                ('count_plan', models.IntegerField(verbose_name='Количество')),
                ('time_plan_ms', models.IntegerField(verbose_name='Плановое время цикла')),
                ('socket_plan', models.IntegerField(verbose_name='Количество гнезд (план)')),
                ('socket_fact', models.IntegerField(verbose_name='Количество гнезд (факт)')),
                ('data_json', models.TextField(verbose_name='Данные JSON')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'db_table': 'tpa_job',
                'ordering': ['date'],
            },
        ),
        migrations.RenameField(
            model_name='cycle',
            old_name='id_machine',
            new_name='machine_id',
        ),
        migrations.AddField(
            model_name='cycle',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('data', models.CharField(max_length=255, verbose_name='События')),
                ('machine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpa.machine')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'db_table': 'tpa_event',
                'ordering': ['date'],
            },
        ),
    ]
