# Generated by Django 4.2.3 on 2023-12-04 13:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tpa', '0008_alter_cycle_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='job',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='tpa.job'),
        ),
    ]
