# Generated by Django 4.2.3 on 2023-12-05 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpa', '0009_cycle_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cycle',
        ),
    ]
