# Generated by Django 4.2.3 on 2023-12-05 05:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tpa', '0010_delete_cycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('time_ms', models.IntegerField(verbose_name='Время цикла')),
                ('count', models.IntegerField(default=0, verbose_name='Количество')),
                ('job', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='tpa.job')),
                ('machine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tpa.machine')),
            ],
            options={
                'verbose_name': 'Цикл',
                'verbose_name_plural': 'Циклы',
                'db_table': 'tpa_cycle',
            },
        ),
    ]
