# Generated by Django 4.2.3 on 2023-12-05 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpa', '0011_cycle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cycle',
            name='machine_id',
        ),
    ]
