# Generated by Django 4.2.3 on 2023-12-05 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tpa', '0012_remove_cycle_machine_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='machine_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tpa.machine'),
        ),
    ]
