# Generated by Django 4.2.3 on 2023-12-05 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpa', '0013_cycle_machine_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cycle',
            old_name='machine_id',
            new_name='machine',
        ),
    ]
