# Generated by Django 4.2.3 on 2023-12-05 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpa', '0014_rename_machine_id_cycle_machine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='machine_id',
            new_name='machine',
        ),
    ]
