# Generated by Django 4.2.3 on 2023-12-05 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpa', '0015_rename_machine_id_event_machine'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cycle',
            table='tpa_cycles',
        ),
        migrations.AlterModelTable(
            name='event',
            table='tpa_events',
        ),
        migrations.AlterModelTable(
            name='job',
            table='tpa_jobs',
        ),
        migrations.AlterModelTable(
            name='machine',
            table='tpa_machines',
        ),
    ]
