# Generated by Django 4.2.3 on 2023-12-05 09:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tpa', '0017_alter_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='uuid_1C',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Идентификатор задания в 1С'),
        ),
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
