# Generated by Django 4.2.3 on 2023-12-05 09:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tpa', '0018_job_uuid_1c_alter_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='count_plan',
            field=models.IntegerField(blank=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='job',
            name='data_json',
            field=models.TextField(blank=True, verbose_name='Данные JSON'),
        ),
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.DateTimeField(blank=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='job',
            name='number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='job',
            name='socket_fact',
            field=models.IntegerField(blank=True, verbose_name='Количество гнезд (факт)'),
        ),
        migrations.AlterField(
            model_name='job',
            name='socket_plan',
            field=models.IntegerField(blank=True, verbose_name='Количество гнезд (план)'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(blank=True, max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='job',
            name='time_plan_ms',
            field=models.IntegerField(blank=True, verbose_name='Плановое время цикла'),
        ),
        migrations.AlterField(
            model_name='job',
            name='uuid_1C',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, verbose_name='Идентификатор задания в 1С'),
        ),
    ]
