# Generated by Django 4.2.3 on 2023-12-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpa', '0019_alter_job_count_plan_alter_job_data_json_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='uuid_1C',
            field=models.UUIDField(blank=True, editable=False, verbose_name='Идентификатор задания в 1С'),
        ),
    ]
