# Generated by Django 4.2.3 on 2023-12-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpa', '0020_alter_job_uuid_1c'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='uuid_1C',
            field=models.CharField(blank=True, max_length=36, verbose_name='Идентификатор задания в 1С'),
        ),
    ]
