# Generated by Django 4.2.3 on 2023-12-26 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tpa', '0021_alter_job_uuid_1c'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='machine',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tpa.machine'),
        ),
        migrations.AlterField(
            model_name='job',
            name='time_plan_ms',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='Плановое время цикла'),
        ),
    ]
