# Generated by Django 4.2.3 on 2024-01-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpa', '0022_job_machine_alter_job_time_plan_ms'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='counter',
            field=models.IntegerField(default=0, verbose_name='Счетчик'),
        ),
    ]
