# Generated by Django 4.2.3 on 2025-10-16 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpa', '0026_machine_full_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='operation_time',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Наработка'),
        ),
    ]
