# Generated by Django 4.2.3 on 2025-10-22 06:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpa', '0027_machine_operation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='operation_time',
            field=models.BigIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Наработка'),
        ),
    ]
