# Generated by Django 4.2.3 on 2026-04-06 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tpa', '0028_alter_machine_operation_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='MashineStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('uuid_1C', models.CharField(blank=True, max_length=36, verbose_name='Идентификатор в 1С')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tpa.mashinestatus')),
            ],
            options={
                'ordering': ('parent__id', 'sort_order', 'name'),
            },
        ),
    ]
