# Generated by Django 4.2.3 on 2026-04-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpa', '0029_mashinestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='mashinestatus',
            name='group',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
