# Generated by Django 4.2.3 on 2026-04-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpa', '0030_mashinestatus_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mashinestatus',
            name='group',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
