# Generated by Django 4.2.3 on 2026-04-07 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpa', '0031_alter_mashinestatus_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mashinestatus',
            options={'ordering': ('parent__id', 'sort_order', 'name'), 'verbose_name': 'Статусы станков', 'verbose_name_plural': 'Статусы станков'},
        ),
        migrations.AlterModelTable(
            name='mashinestatus',
            table='tpa_machine_statuses',
        ),
    ]
