# Generated by Django 4.2.3 on 2026-04-07 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpa', '0032_alter_mashinestatus_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mashinestatus',
            table='tpa_mashinestatus',
        ),
    ]
