# Generated by Django 4.2.3 on 2026-04-07 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpa', '0034_machine_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='status',
        ),
    ]
