# Generated by Django 4.2.3 on 2026-04-07 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tpa', '0035_remove_machine_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tpa.mashinestatus'),
        ),
    ]
