# Generated by Django 4.2.3 on 2026-04-07 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tpa', '0037_alter_machine_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MashineStatus',
            new_name='MachineStatus',
        ),
        migrations.AlterModelTable(
            name='machinestatus',
            table='tpa_machinestatus',
        ),
    ]
