# Generated by Django 4.2.3 on 2026-04-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpa', '0038_rename_mashinestatus_machinestatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinestatus',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Код'),
        ),
    ]
