# Generated by Django 4.2.3 on 2024-10-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное наименование')),
                ('code_1C', models.CharField(max_length=11, verbose_name='Код 1С')),
                ('uuid_1C', models.CharField(blank=True, max_length=36, verbose_name='Идентификатор задания в 1С')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
                'db_table': 'pr_partner',
            },
        ),
    ]
