# Generated by Django 4.2.3 on 2024-10-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='uuid_1C',
            field=models.CharField(blank=True, max_length=36, verbose_name='Идентификатор партнера в 1С'),
        ),
    ]
