# Generated by Django 4.2.3 on 2025-02-11 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Параметр',
                'verbose_name_plural': 'Параметры',
                'db_table': 'sn_parameters',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Сенсор',
                'verbose_name_plural': 'Сенсоры',
                'db_table': 'sn_sensors',
            },
        ),
        migrations.CreateModel(
            name='WorkArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Рабочий участок',
                'verbose_name_plural': 'Рабочие участки',
                'db_table': 'sn_work_areas',
            },
        ),
        migrations.CreateModel(
            name='ValueParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(db_index=True, verbose_name='Дата')),
                ('value', models.DecimalField(blank=True, decimal_places=3, max_digits=9, verbose_name='Значение')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.parameter')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.sensor')),
            ],
            options={
                'verbose_name': 'Значение параметра',
                'verbose_name_plural': 'Значения параметров',
                'db_table': 'sn_values_parameters',
            },
        ),
        migrations.AddField(
            model_name='sensor',
            name='work_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.workarea'),
        ),
    ]
