# Generated by Django 4.2.3 on 2023-07-21 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pressform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('article', models.CharField(max_length=50, verbose_name='Артикул')),
                ('date_start', models.DateField(default=datetime.date(2000, 1, 1), verbose_name='Дата начала')),
                ('date_finish', models.DateField(default=datetime.date(2000, 1, 1), verbose_name='Дата окончания')),
                ('type', models.IntegerField(choices=[(0, '-'), (1, 'Наша'), (2, 'Клиента'), (3, 'Импортная')], default=0, verbose_name='Тип прессформы')),
                ('status', models.IntegerField(choices=[(0, '-'), (1, 'В работе'), (2, 'Выполнена')], default=0, verbose_name='Статус')),
                ('year', models.IntegerField(default=0, verbose_name='Год выпуска')),
            ],
            options={
                'verbose_name': 'Прессформа',
                'verbose_name_plural': 'Прессформы',
                'db_table': 'pressform',
            },
        ),
    ]
