# Generated by Django 4.2.3 on 2023-07-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pressforms', '0002_alter_pressform_date_finish_alter_pressform_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressform',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год выпуска'),
        ),
    ]
