# Generated by Django 4.2.3 on 2023-07-25 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pressforms', '0003_alter_pressform_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressform',
            name='date_finish',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='pressform',
            name='date_start',
            field=models.DateField(verbose_name='Дата начала'),
        ),
    ]
