# Generated by Django 4.2.3 on 2023-07-25 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pressforms', '0004_alter_pressform_date_finish_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('priority', models.IntegerField(verbose_name='Очередность')),
            ],
            options={
                'verbose_name': 'Тип работы',
                'verbose_name_plural': 'Типы работ',
                'db_table': 'type_work',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('priority', models.IntegerField(default=0, verbose_name='Очередность')),
                ('done', models.IntegerField(choices=[(0, '-'), (1, 'Зеленая'), (2, 'Синяя'), (3, 'Желтая'), (4, 'Красная')], default=0, verbose_name='Выполнение')),
                ('week', models.IntegerField(default=0, verbose_name='Номер недели')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pressforms.typework')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
                'db_table': 'work',
            },
        ),
    ]
