# Generated by Django 4.2.3 on 2023-07-26 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pressforms', '0005_typework_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='done',
        ),
    ]
