# Generated by Django 4.2.3 on 2023-07-31 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pressforms', '0008_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='pressform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pressforms.pressform', unique=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pressforms.work', unique=True),
        ),
    ]
