# Generated by Django 4.2.3 on 2023-07-31 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pressforms', '0009_alter_progress_pressform_alter_progress_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='pressform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pressforms.pressform'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pressforms.work'),
        ),
    ]
