# Generated by Django 4.2.3 on 2023-07-31 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pressforms', '0010_alter_progress_pressform_alter_progress_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressform',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='Очередность'),
        ),
        migrations.AddField(
            model_name='pressform',
            name='shield',
            field=models.BooleanField(default=False, verbose_name='Шильда'),
        ),
    ]
