# Generated by Django 4.2.3 on 2023-07-31 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pressforms', '0011_pressform_priority_pressform_shield'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressform',
            name='assembly',
            field=models.CharField(default='', max_length=255, verbose_name='Сборка'),
        ),
    ]
