# Generated by Django 4.2.3 on 2023-07-31 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pressforms', '0012_pressform_assembly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressform',
            name='assembly',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Сборка'),
        ),
        migrations.AlterUniqueTogether(
            name='progress',
            unique_together={('pressform', 'work')},
        ),
    ]
