# Generated by Django 4.2.3 on 2023-11-16 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pressforms', '0013_alter_pressform_assembly_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pressform',
            table='pf_pressform',
        ),
        migrations.AlterModelTable(
            name='progress',
            table='pf_execute',
        ),
        migrations.AlterModelTable(
            name='typework',
            table='pf_type_work',
        ),
        migrations.AlterModelTable(
            name='work',
            table='pf_work',
        ),
    ]
