# Generated by Django 4.2.3 on 2024-04-02 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pressforms', '0014_alter_pressform_table_alter_progress_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressform',
            name='date_modified',
            field=models.DateField(auto_now=True),
        ),
    ]
