# Generated by Django 4.2.3 on 2024-04-02 06:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pressforms', '0016_alter_pressform_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressform',
            name='date_modified',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата изменения'),
        ),
    ]
