# Generated by Django 4.2.3 on 2024-04-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pressforms', '0017_alter_pressform_date_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('file', models.FileField(upload_to='instrumentalka')),
                ('type', models.IntegerField(choices=[(0, 'Видео'), (1, 'Фото')], default=0, verbose_name='Тип контента')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Медиа файлы',
                'db_table': 'pf_mediafiles',
            },
        ),
        migrations.AlterField(
            model_name='pressform',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
    ]
