# Generated by Django 4.2.3 on 2024-04-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pressforms', '0018_mediafile_alter_pressform_date_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='date_finish',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выполнения'),
        ),
        migrations.AlterField(
            model_name='pressform',
            name='type',
            field=models.IntegerField(choices=[(0, '-'), (1, 'Европартнер'), (2, 'Клиент'), (3, 'Импорт')], default=0, verbose_name='Тип прессформы'),
        ),
    ]
