# Generated by Django 4.2.3 on 2024-10-23 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0002_alter_partner_uuid_1c'),
    ]

    operations = [
        migrations.CreateModel(
            name='mw_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное наименование')),
                ('article', models.CharField(max_length=50, verbose_name='Артикул')),
                ('assembly', models.CharField(blank=True, default='', max_length=255, verbose_name='Сборка')),
                ('date_start', models.DateField(verbose_name='Дата начала')),
                ('date_finish', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('priority', models.IntegerField(default=0, verbose_name='Очередность')),
                ('status', models.IntegerField(choices=[(0, '-'), (1, 'В работе'), (2, 'Выполнена')], default=0, verbose_name='Статус')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год выпуска')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.partner')),
            ],
            options={
                'verbose_name': 'Деталь',
                'verbose_name_plural': 'Детали',
                'db_table': 'mw_detail',
            },
        ),
        migrations.CreateModel(
            name='mw_Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('priority', models.IntegerField(default=0, verbose_name='Очередность')),
            ],
            options={
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы',
                'db_table': 'mw_work',
            },
        ),
        migrations.CreateModel(
            name='mw_Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0, verbose_name='Выполнение')),
                ('week', models.IntegerField(default=0, verbose_name='Неделя')),
                ('date_finish', models.DateField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metalworks.mw_detail')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metalworks.mw_work')),
            ],
            options={
                'verbose_name': 'Выполнение',
                'verbose_name_plural': 'Выполнение',
                'db_table': 'mw_execute',
                'unique_together': {('detail', 'work')},
            },
        ),
    ]
