# Generated by Django 4.2.3 on 2024-10-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metalworks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mw_detail',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='mw_detail',
            name='uuid_1C',
            field=models.CharField(blank=True, max_length=36, verbose_name='Идентификатор партнера в 1С'),
        ),
    ]
