# Generated by Django 4.2.3 on 2024-10-24 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_alter_partner_uuid_1c'),
        ('metalworks', '0002_mw_detail_quantity_mw_detail_uuid_1c'),
    ]

    operations = [
        migrations.AddField(
            model_name='mw_detail',
            name='shield',
            field=models.BooleanField(default=False, verbose_name='Шильда'),
        ),
        migrations.AlterField(
            model_name='mw_detail',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partners.partner', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='mw_detail',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Количество, шт.'),
        ),
        migrations.AlterField(
            model_name='mw_detail',
            name='uuid_1C',
            field=models.CharField(blank=True, max_length=36, verbose_name='Идентификатор детали в 1С'),
        ),
    ]
