# Generated by Django 4.2.3 on 2024-10-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metalworks', '0003_mw_detail_shield_alter_mw_detail_partner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mw_detail',
            name='type',
            field=models.IntegerField(choices=[(0, '-'), (1, 'Европартнер'), (2, 'Клиент'), (3, 'Импорт')], default=0, verbose_name='Тип прессформы'),
        ),
    ]
